import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import QueryProvider from "@/components/QueryProvider";

import "./globals.css";

const roboto = Roboto({
  weight: '400',
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <QueryProvider >
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
